### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by ties**
Hi,

Last summer I used this library during an internship. During the internship I was working on a Django app which was compatible with both Python 2.7 and 3.4.

I made some small patches to your library to add Python 3 support. I juste cleaned up the test framework to get the Travis tests running on all combinations of supported Python and Django versions.

Please look at it carefully, I needed some iterations to get the travis scripts right.

If you want me to rebase/squash these commits I understand that.

### CODE REVIEW

**Comment by lawlesst** [comment]
Ties,

Python 3 support sounds great.  Thanks for contributing this.  Let me take
a closer look and get back to you.

Ted

**Comment by jersey99** [comment]
Hi,

Any update on this? ties, any caveats in using your fork of python3? I am trying to get shibboleth working with an app I wrote in django.

Cheers!

**Comment by bbusenius** [comment]
We're wondering about the status of this pull request too. We'd be happy to help if there's a specific problem holding this up. Otherwise, should we just use Ties' fork?

**Comment by jersey99** [comment]
bbusenius,

FYI, I have been running ties's version successfully, I don't see any issues as of now.

**Comment by ties** [comment]
@all: As far as I know this branch should work. It was worked without problems in the Django application I was integrating it in.

I have not tested it with Python 3.5/Django 1.8. If no alternative is available I recommend that this branch is merged.

**Comment by bcail** [comment]
Sorry for the delay, and thanks for contributing this PR. Merging it now.

**Comment by ties** [comment]
Thanks for merging the feature 😊

**Pull request merged**
